annotations:
  path: /actuator/prometheus
  port: "8080"
  scrape: "true"
env:
  postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
  postgresUser: pg_root
  postgresPassword: test_pg
  reportPath: /logs/reports
  logPath: /logs
service:
  port: 8080
revisionHistoryLimit: 15
replicas: 1
strategy:
### Опишите стратегию RollingUpdate для бэкенда
image: verhanasta/sausage-backend:latest
imagePullPolicy: Always
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "1"
containerPort: 8080
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
### Опишите LivenessProbe для бэкенда
vpa:
  enabled: true
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: "150m"
          memory: "256Mi"
        maxAllowed:
          cpu: "1"
          memory: "512Mi"