imagePullPolicy: Always
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate
service:
  port: 80
ingress:
  host: front-verhanasta.2sem.students-projects.ru # Корректный домен будет указан в задании
  path: /
  pathType: Prefix
containerPort: 80
image: verhanasta/sausage-frontend:latest
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "1"
nginxConf: nginx.conf
