imagePullPolicy: Always
###vault:
###  host: ip
###  name: vault
###  vaultToken: someToken
revisionHistoryLimit: 10
image: verhanasta/backend-report:latest
replicas: 1
strategy:
  type: Recreate
containerPort: 8080
env:
  port: "8080"
  db: "mongodb://mongo_root:test_mongo@mongodb:27017/sausage-store?authSource=admin"
request:
  cpu: 100m
limits:
  cpu: 1
autoscaling:
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 75
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 20
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilizationPercentage: 60
  averageUtilization: 75
