CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    picture_url varchar(255)
);

CREATE TABLE product_info (
    product_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    price double precision
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    status varchar(255)
);

CREATE TABLE orders_date (
    order_id bigint NOT NULL,
    status varchar(255),
    date_created date DEFAULT current_date
);

CREATE TABLE order_product (
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);